name: test

on: [push]

jobs:
  phpunit:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: composer install
        
      - name: Run tests
        run: vendor/bin/phpunit tests/Report --bootstrap vendor/autoload.php
